### ISSUE TITLE
SimpleHttpClient refuses to send requests to localhost

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#184]
Attempting to connect to a localhost results in uncaught exception and 404 status code.

I set up a local server to test SimpleHttpClient with the following code
~~~java
  public static void main(String[] args) throws Throwable {
    HttpClient http = HttpClientFactory.getClient(null);
    var url = URI.create("http://localhost:5000");
    var response = http.get(url).execute();
    System.out.println(response.getStatusCode());
  }
~~~
It runs properly in java when using SimpleHttpClient or ApacheHttp.
In js, However, no request reaches the server, status code is 404 and there is an exception:
~~~
clazz {__JSID__: 932, stackTrace: Array(5), cause: clazz, detailMessage: "opening http://localhost:5000"}
cause: clazz {__JSID__: 932, stackTrace: Array(5), cause: clazz, detailMessage: "opening http://localhost:5000"}
detailMessage: "opening http://localhost:5000"
stackTrace: (5) [{…}, {…}, {…}, {…}, {…}, __BYTESIZE: 0, __JSID__: 933, getClass$: ƒ, hashCode$: ƒ, equals$O: ƒ, …]
__JSID__: 932
__proto__: Object 
~~~

**Comment by warownia1** [comment]
Setting up a reverse tunnel to the localhost and making request to that remote host works almost fine (see issue #183)

**Comment by warownia1** [comment]
@BobHanson could you take a look at it? It's not urgent, but it would be useful to be able to test with a local server.

**Comment by BobHanson** [comment]
Pretty sure people do this all the time. If your machine is reporting a
404, then that's what it is. Missing file. So it is just something with
your configuration.

Some tests:

1. Use a standard AJAX call, not anything to do with Jalview or SwingJS.
Thus, from a browser developer console after loading any page from the
local site that has jQuery enabled.

x = $.ajax({src: "http://localhost:5000/files/readme"});

2. Try targeting a specific page rather than an implicit default page.


Note that you can't access an HTTP page from an HTTPS page. And unless your
local host is CORS-enabled, you can't make AJAX calls to it from any other
site. But I think you are doing calls from localhost:5000 already. Yes?

**Comment by warownia1** [comment]
I think that's not it.
Let me describe what I did:
First, I set up a dummy Python server listening on port 5000 which sends a following HTTP response on `/index` path (changed from default as you suggested)
~~~
HTTP/1.0 201 CREATED
Content-Type: text/html; charset=utf-8
Content-Length: 11
Access-Control-Allow-Origin: *
Server: Werkzeug/1.0.1 Python/3.7.9
Date: Thu, 03 Dec 2020 13:18:22 GMT

Hello world
~~~
The java code I posted above (with updated path) connects to the server and prints 201 when run in Java (request and 201 response appears in the server log). So does 
~~~
$.ajax("http://localhost:5000/index")
  .done(function(data, status, jqXHR) { console.log(jqXHR.status); });
~~~
(this doesn't work when `Access-Control-Allow-Origin: *` is not present)

But, when I set up a server on port 8000 hosting the transpiled java code it doesn't contact the server on localhost:5000 and immediately prints 404.

It's not limited to my local server, using `http://httpstat.us/201` yields identical result.
Interestingly

**Comment by warownia1** [comment]
PS. I also tried opening the swingjs site directly from the filesystem through `file://` but it didn't work either.

**Comment by BobHanson** [comment]
Right -- not allowing file:// generally!  but File(), FileInputStream(), and FileOutputStream() are all allowed. Input provided the path is within the path of the hosting local web page.

**Comment by warownia1** [comment]
I think you misunderstood. I entered the website with `file:///home/myusername/swinjstest/site/testing_Main.html` address to rule out server issues. It has nothing to do with sending files. I'm testing all that stuff with empty GET requests.

**Comment by warownia1** [comment]
Not sure if it matters, but I noticed that requests that arrive from javascript SimpleHttpClient are HTTP/1.0

**Comment by BobHanson** [comment]
meaning...

**Comment by BobHanson** [comment]
Question: is test.Test_HTTP working for you?

**Comment by BobHanson** [comment]
When I try to access https://httpstat.us/201 from Java, it reports a 403 code, not 201. But JavaScript is working, oddly enough.

at file:///C:/Users/hansonr/git/java2scriptH/sources/net.sf.j2s.java.core/site/test_Test_HTTP.html

Testing httpstat 201
httpstat.us reports 201
httpstat.us reports 201 Created

from file:///C:/Users/hansonr/git/java2scriptH/sources/net.sf.j2s.java.core/src/test/Test_HTTP.java

	static {
		/** @j2sNative 
		J2S.addDirectDatabaseCall("www.compbio.dundee.ac.uk/slivka");
		
		J2S.addDirectDatabaseCall("httpstat.us");

		 */

	}
...
		System.out.println("Testing httpstat 201");
		
		try {
			URL url = new URL("http://httpstat.us/201");
			HttpURLConnection c = (HttpURLConnection) url.openConnection();
			int code = c.getResponseCode();
			System.out.println("httpstat.us reports " + code);
			InputStream oi = url.openStream();
			String s = new String(oi.readAllBytes());
			System.out.println("httpstat.us reports " + s);
		} catch (IOException e) {
			System.out.println(e);
		}

**Comment by warownia1** [comment]
Aren't you sending an empty request with no method nor headers?
When I sent this minimal request to httpstat.us using netcat it worked just fine:
~~~
GET /201 HTTP/1.1
Host: httpstat.us
User-Agent: netcat
Accept: */*

~~~

**Comment by warownia1** [comment]
test_Test_HTTP.html gives my this output in javascript (trimmed the rest of the test):
~~~
Testing httpstat 201
httpstat.us reports 200
httpstat.us reports 201 Created
~~~
and this in Java
~~~
Testing httpstat 201
httpstat.us reports 201
httpstat.us reports 201 Created
~~~

**Comment by BobHanson** [comment]
J2S is set to use a relay whenever a site is accessed that is not in its "direct call" database. This was mostly a workaround for Jmol users accessing sites that did not implement CORS. It can be turned off completely with

J2S.addDirectDatabaseCall(".");

because "." will be found in any URL.

Are you sure you have  that static call in there now? What is your browser developer console saying? Is it accessing chemapps.stolaf.edu? 200 is the message that server would send.

**Comment by BobHanson** [comment]
BTW the reason JavaScript is reporting 400 instead of 405 is that it is a CORS PUT method CORS access exception at slivka, not because it couldn't report 405. I guess there is no HTTP ResponseCode for a CORS error.

**Comment by BobHanson** [comment]
Back to the original question: localhost:5000 from localhost:8000

Please in general, with a JavaScript issue, from your browser's developer console clip out the relevant messages into these issue 

conclusion to this issue privately.

**Comment by BobHanson** [comment]
Just following up with some thoughts. I am sure to you it seems crazy to do this business with the relay. The history of this is  that all this code predates the big move to https around 2016-19 and also the rise of CORS around 2014 (I think). So there was a period there when many database servers either hadn't set their CORS settings or had just implemented them or implemented them incorrectly, and also many more pages started showing up using https and could therefore no longer access the non-https databases directly. Thus the need for such indirect means for the thousands of web sites that utilize Jmol and the many databases that Jmol draws from. 

That said, maybe it is time to just set the default to "no relay".  Or just implement those for Jmol and not SwingJS in general, or just "legacy" Jmol 14.x and not Jmol-SwingJS (Jmol 15.x). 

I will think about it. I'm certainly not against removing it entirely.

Bob
