### ISSUE TITLE
singleThreadExecutor doesn't start about 7% of submitted tasks.

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#204]
Roughly 7% of the tasks submitted to the executor are never started. There are no errors and tasks are simply not started and remain in the "Not completed" state. Both `Future#isDone` and `Future#isCancelled` return false.

This is the code I used for testing:

~~~java
public class Main extends JFrame {
  
  ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
  
  Main() {
    super("My Frame");
    setVisible(true);
    setSize(400, 300);
    
    final Set<Integer> pending = new HashSet<>();
    final int N = 1000;
    
    JButton button = new JButton("CHECK");
    button.addActionListener((event) -> {
      System.out.format("completion %f%%%n", (100 - 100f * pending.size() / N));
    });
    add(button);
    
    for (int j = 0; j < N; ++j) {
      final int i = j;
      pending.add(i);
      var task = executor.submit(() -> {
        long startTime = System.currentTimeMillis();
        while (System.currentTimeMillis() <= startTime + 10);
        pending.remove(i);
        System.out.format("finished %d%n", i);
      });
    }
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> new Main());
  }
}
~~~

**Comment by BobHanson** [comment]
This is fixed. It was simply that ThreadPoolExecutor needed at least one millisecond delay to properly set up the tasks. See new SwingJS-site.zip

**Comment by BobHanson** [comment]
java2script 3.3.1-v3 transpiler update, including Java 11. has been pushed.

**Comment by BobHanson** [comment]
This is not a generally acceptable way in JavaScript to wait. Is this
supposed to be representative of real code?

while (System.currentTimeMillis() <= startTime + 10);

Implemented as a simple StateMachine in test.Test_Exec and working properly
now. The problem was that ThreadPoolExecutor needed a millisecond delay to
properly set up the tasks.

**Comment by warownia1** [comment]
There is not waiting in the real code, I just needed the task to take some time for testing purposes.
