### ISSUE TITLE
Annotations not present in transpiled code

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#229]
Annotations on methods and classes are not present when introspecting the definitions in runtime.
e.g. in the following code:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface MyAnnotation {}

public class AnnotationExample {
  public static void main(String[] args) throws Exception {
    Method method = AnnotationExample.class.getMethod("annotated");
    method.getAnnotations();  // contains annotation in java but empty array in js
  }
  
  @MyAnnotation
  public void annotated() {}
}
```
java correctly reports one annotation on the method, but javascript gives an empty array.

**Comment by BobHanson** [comment]
SwingJS does not track annotations the way Java does. It identifies a few
that it needs only

**Comment by warownia1** [comment]
Are there plans to support annotations in the future? I don't really need them, so no pressure.

**Comment by foreveremain** [comment]
Hi Bob - I can see some commits experimenting with runtime retention - do you think it is going to be possible to have runtime annotation discovery in JS ?  we (including @benzoid) are thinking about how to run Jalview's test suite (or a simple subset thereof) via JalviewJS.

**Comment by BobHanson** [comment]
I think this is working, right? See test.Test_Annotation_impl.java

**Comment by BobHanson** [comment]
This is fixed.

// BH 2022.06.27 -- 3.3.1-v5 fixes missing method annotations
Note that the list of annotations to skip by default is in .j2s



Bob
