### ISSUE TITLE
Invalid File path when using URL from class loader.

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#234]
File paths are constructed incorrectly when opening a File constructed using a URL obtained from a class loader. ``/swingjs/j2s/`` prefix if prepended to the path twice.

Example:
```java
package org.example;
public class ResourcePathTest {
  public static void main(String[] args) throws Exception {
    URL url = ResourcePathTest.class.getResource("resource.txt");
    File file = new File(url.toURI());
    BufferedReader fr = new BufferedReader(new FileReader(file));
    try (fr) {
      System.out.println(fr.readLine());
    }
  }
}
```
Running this code in javascript causes an uncaught *FileNotFoundException: Opening file /swingjs/j2s/org/example/resource.txt*.
A debugger shows that the `url.path` and the `file.path` are both *"/swingjs/j2s/org/example/resource.txt"* and point to an existing resource. However, attempting to read the file sends a new request to */swingjs/j2s//swingjs/j2s/org/example/resource.txt* which does not exist.

**Comment by BobHanson** [comment]
this was fixed in 2022
