### ISSUE TITLE
Default methods defined in the Comparator interface not present on instances.

### ISSUE THREAD

**Issue by warownia1** [BobHanson/java2script#247]
Default methods of the `java.util.Comparator` interface, despite being present in the transpiled code, are not present on the comparator objects instantiated using static factory methods of the `Comparator` interface. Those methods are crucial for comparators to work properly.

Example:
```java
class StringLengthExtractor implements Function<String, Integer> {
  @Override
  public Integer apply(String t) { return t.length(); }
}

class FirstLetterExtractor implements Function<String, Character> {
  @Override
  public Character apply(String t) { return t.charAt(0); }
}
```

```java
var lenExtractor = new StringLengthExtractor();
var flExtractor = new FirstLetterExtractor();
var list = new ArrayList<String>(List.of(
    "alpha", "bravo", "charlie", "delta", "eve"
));
var comparator = Comparator.comparing(lenExtractor);
comparator = comparator.thenComparing(flExtractor);
list.sort(comparator);
System.out.println(list);
```

Running the code above throws `TypeError: comparator.thenComparing$java_util_function_Function is not a function`. Inspecting the object in a debugger shows that the object does not contain any methods defined in the interface it implements.

I believe this problem applies to any use of default methods which are widely adopted in JDK1.8.

**Comment by BobHanson** [comment]
Indeed. Failure to check if the class was a lambda expression when parsing "this.compare(a,b)" within a lambda expression within Compare.thenComparing(). Result was that "this" was used directly rather than  this.b$['java.util.Comparator']

fixed; will push in +10 h
