### ISSUE TITLE
Drop java.io.File._bytes when object is no longer referenced

### ISSUE THREAD

**Issue by foreveremain** [BobHanson/java2script#29]
Cached File contents need to be cleared up when references to the file object have gone away.

**Comment by BobHanson** [comment]
It's not possible in JavaScript to track all references to a resource the way it is in Java. The call to clear a cached file is to delete the file, same as in Java. However, if you hold on to File objects, they might still contain a reference to the byte[ ] array of the contents for that file, so you will need to manage those. 

In addition, for general resources, you can clear the cache by explicitly caching null for the contents using:

jsutil.cachePathData(String path, Object data)

where jsutil is an instance of swingjs.JSUtil, created (by you) using Class.forName().newInstance() and accessed through the swingjs.api.JSUtilI interface.
